name: CI

on:
  push:
    branches:
    - release
    - develop
  pull_request:
    branches:
    - develop

  workflow_dispatch:

jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - name: Config & Build
        run: | 
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE=Release -B./build -G "Unix Makefiles"
          cmake --build ./build
      - name: Unit test (GoogleTest)
        run: |
          ./build/bin/testBase64
          
  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - name: Config & Build
        run: | 
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -B./build -G "Visual Studio 16 2019" -T host=x64 -A x64
          cmake --build ./build --config Release --target ALL_BUILD
      - name: Unit test (GoogleTest)
        run: |
          ./build/bin/Release/testBase64.exe
